### ISSUE TITLE
Feature: 1. User can search for a list of manga by title

### ISSUE THREAD

**Issue by luiderek** [luiderek/ajax-project#1]
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users using a search bar from a pop-out sidebar will create summary card dom elements that fill the page with data pulled from the jikan API.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/12964172/163635289-3e772614-a19c-4e6b-97e2-d6cd9aa099ce.png)
![image](https://user-images.githubusercontent.com/12964172/163635792-c6f15ea1-1b5f-41ac-ad50-cfca25d07cf1.png)
![image](https://user-images.githubusercontent.com/12964172/163635313-371bf2c7-94c1-43b1-a1d8-fafa1949f7d5.png)
![image](https://user-images.githubusercontent.com/12964172/163635422-b1e7265f-51d5-408c-9453-ecc71a7fbe43.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Settle CSS for containers 
- [x] Create a title bar row element with a side menu-button
- [x] On pressing menu button, create a sidebar
- [x] Have the sidebar have a search bar
- [x] Have a background fade effect for out of focus elements
- [x] Be able to get a JSON reply from an API search
- [x] Be able to manipulate the JSON to get the relevant data
- [x] Create a dummy card to figure out HTML / CSS - putting on hold
- [x] create a function that renders cards depending on the data object
- [x] create a data object from the API call
- [x] Have a mobile-desktop transition
- [x] Remove all CSS properties that have no effect.
- [x] Remove all console logs, commented out code.

for later
- [ ] adjust sidebar scaling logic / animations / effects on menu button
- [x] adjust card layout logic to actually behave properly
- [ ] Make sure container deals with cards properly
