### ISSUE TITLE
Polish: 5. Improve looks

### ISSUE THREAD

**Issue by luiderek** [luiderek/ajax-project#10]
## ✅ Task List

- [x] Add a brief motion animation for the sidebar coming in and out if possible.
- [x] Have demographics and themes listed along with the genre tags.
- [x] Have the "My List" sidebar link have a counter reflecting the length of the list.
- [x] Deal with synopsis overflow in a more sane way
- [x] Figure out why themes/genres/demos aren't loading after first load.

> ##### Commit checklist for tasks needed.
> ## move to future issue, just needed a push to go out to see the changes to git deploy

- [ ] Make the detail modal look better
  - [ ] Move the save / remove button to the bottom right
- [ ] also filter out "(", on top of "[" for the synopsis descriptions
- [ ] Figure out how to have some form of page swapping / infinite scroll
- [ ] Make sure API calls are rate-limited.
