### ISSUE TITLE
Feature: User can export and import saved lists

### ISSUE THREAD

**Issue by luiderek** [luiderek/ajax-project#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

There will be an input labled "load list" that can replace data.saved if it's a valid object
And a box that will update on click that will save to clipboard some sort of code, base 64 or something of the JSON object containing the saved list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create dummy save / load text areas fixed to the bottom of the menubar.
- [x] Find out how to fill a clipboard on interaction
- [x] Be able to save and load data.saved from plaintext objects.
- [x] Find library or method that is able to compress the data.saved JSON object into fewer characters
- [x] Replace alert with cuter looking notification on save.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] find a fix to the bug where demo/genre/themes don't load on first load.
- [x] Fix bug where manga without demographic data are unable to switch to detail mode
- [ ] Process the data that goes into data.saved better to reduce the amount of data to carry over.
- [ ] Have some sort of validation and error handling for data loading for security / sanity.
- **Clean Up**
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
