### ISSUE TITLE
Responsiveness Polish

### ISSUE THREAD

**Issue by luiderek** [luiderek/ajax-project#14]
## ✅ Task List

> ##### Commit checklist for tasks needed.
- [x] interactables have pointer cursor
- [x] UI looks passable on mobile, tablet, desktop
- [x] loading spinner for API call
- [x] empty result message
- [x] check for typos
