### ISSUE TITLE
update color pallate

### ISSUE THREAD

**Issue by luiderek** [luiderek/ajax-project#17]
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] get a new color theme for overall menu items
- [x] make sure the colors for interactables are consistent
- [x] have a subtle interactable color shift on hover
