### ISSUE TITLE
Feature: 2. User can filter search based on genre

### ISSUE THREAD

**Issue by luiderek** [luiderek/ajax-project#2]
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can use dropdown menus below the search bar to filter the api search by the target demographic and the publishing status.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create data objects to store filters
- [x] get a list of genres from the API
- [x] from the genre list, make a list of checkboxes
- [x] have functionality so checkboxes can swap between 3 modes
- [x] make the checkboxs relate to the data object
- [x] be able to hide the checkbox list of genres from a dropdown click
- [x] make sure the API call is working as intended
- [x] set a max and minimum width to the sidebar
- [ ] Remove all console logs, commented out code.
- [x] Remove all CSS properties that have no effect.
