### ISSUE TITLE
Feature: 3. User can filter search by themes, status, demographics

### ISSUE THREAD

**Issue by luiderek** [luiderek/ajax-project#3]
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can use dropdown menus below the search bar to filter the api search by status, demographics, and themes.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] adjust the data object to have a place to store demographics, themes
- [x] have a function to call the API to get the list of themes, demographics
- [x] create a new dropdown menu for themes, demographics
- [x] create a new dropdown menu for statuses with clickable toggles / dropdown
- [x] adjust the data object to have a place to store status filters
- [x] adjust the API call function to deal with status inclusion/exclusion
- [x] Remove all console logs, commented out code.
- [ ] Remove all CSS properties that have no effect.
