### ISSUE TITLE
Feature: 4. User can add, remove items into a saved list

### ISSUE THREAD

**Issue by luiderek** [luiderek/ajax-project#4]
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When clicking items in the search view, a detail view will come up. From there, entries can be added, or removed from a saved list in local-storage. Users will use the sidebar to get into the list view, and the search bar to return to the default search/browse mode.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/12964172/163648363-b1cd572a-19d0-45bf-abb5-67ef01b9876b.png)
![image](https://user-images.githubusercontent.com/12964172/163648385-7aac3c8b-4d76-4ab3-a071-020584670d76.png)
![image](https://user-images.githubusercontent.com/12964172/163648399-56011ee6-7459-46ba-a803-111425e396e6.png)
![image](https://user-images.githubusercontent.com/12964172/163648433-830b915d-2bc2-4c93-8e34-7723b838705f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Have a response if API returns nothing
- [x] decide on the details that actually need to be carried over to the entry array 
- [x] Have a detail view that expands on clicking on other cards
  - [x] add an event listener that watches the container 
  - [x] from that be able to distinguish from the object in data.entry
  - [x] create a popup modal if a card element is clicked
  - [x] write a function to create dom elements that populates the modal
  - [x] write CSS to make the elements look better
- [x] on the detail view, have an add button, that becomes a nonfunctional remove button on press
  - [x] when add is clicked, make a copy of the data.entry into a new storage array
- [x] within the sidebar, add a "My List" link to view-swap
- [x] write a new rendering function 
  - [x] while on List view, have searches return user to the search view
- [ ] Remove all console logs, commented out code.
- [ ] Remove all CSS properties that have no effect.
