### ISSUE TITLE
Feature: 5. User can remove items from a saved list

### ISSUE THREAD

**Issue by luiderek** [luiderek/ajax-project#5]
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When clicking items in the search or list view, a detail view will come up. From there, entries can be removed from the saved list DOM and from the data object. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/12964172/163649090-ac51841f-3477-4a4f-a5bc-9e94d057eb21.png)
![image](https://user-images.githubusercontent.com/12964172/163649105-8cc0b176-8370-432f-9500-36cd55adad6d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ] Have a detail view that expands on clicking on other cards
- [ ] on the detail view from list view have a new button for remove 
- [ ] have the remove button remove an entry from the data object
- [ ] Remove all console logs, commented out code.
- [ ] Remove all CSS properties that have no effect.
